package surreal.bpcatacombs.item;

import net.minecraft.item.*;
import net.minecraftforge.common.util.EnumHelper;
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;
import net.minecraftforge.fml.common.registry.GameRegistry.ObjectHolder;
import surreal.bpcatacombs.ImmersiveEngineering;
import surreal.bpcatacombs.Tags;
import surreal.bpcatacombs.internal.registration.Registry;

@ObjectHolder(Tags.MOD_ID)
public class BPCItems extends Registry<Item> {

    public static final Item.ToolMaterial STEEL = EnumHelper.addToolMaterial("steel",  3, 641, 7.0F, 3.0F, 10);

    public static final Item MOLD_PLATE = null;
    public static final Item MOLD_GEAR = null;
    public static final Item MOLD_ROD = null;
    public static final Item MOLD_BULLET_CASING = null;
    public static final Item MOLD_WIRE = null;
    public static final Item MOLD_MOLD_PACKING_4 = null;
    public static final Item MOLD_MOLD_PACKING_9 = null;
    public static final Item MOLD_UNPACKING = null;
    public static final Item STICK_TREATED = null;
    public static final Item STICK_IRON = null;
    public static final Item STICK_STEEL = null;
    public static final Item STICK_ALUMINIUM = null;
    public static final Item HEMP_FIBER = null;
    public static final Item HEMP_FABRIC = null;
    public static final Item ERSATZ_LEATHER = null;
    public static final Item COAL_COKE = null;
    public static final Item SLAG = null;
    public static final Item COMPONENT_IRON = null;
    public static final Item COMPONENT_STEEL = null;
    public static final Item COMPONENT_ELECTRONIC = null;
    public static final Item COMPONENT_ELECTRONIC_ADV = null;
    public static final Item WATERWHEEL_SEGMENT = null;
    public static final Item WINDMILL_BLADE = null;
    public static final Item WINDMILL_SAIL = null;
    public static final Item WOODEN_GRIP = null;
    public static final Item GUNPART_BARREL = null;
    public static final Item GUNPART_DRUM = null;
    public static final Item GUNPART_HAMMER = null;
    public static final Item DUST_COKE = null;
    public static final Item DUST_HOP_GRAPHITE = null;
    public static final Item INGOT_HOP_GRAPHITE = null;
    public static final Item WIRE_COPPER = null;
    public static final Item WIRE_ELECTRUM = null;
    public static final Item WIRE_ALUMINIUM = null;
    public static final Item WIRE_STEEL = null;
    public static final Item WIRE_LEAD = null;
    public static final Item DUST_SALTPETER = null;
    public static final Item DUST_SULFUR = null;
    public static final Item DUST_WOOD = null;
    public static final Item LIGHT_BULB = null;
    public static final Item ELECTRON_TUBE = null;
    public static final Item CIRCUIT_BOARD = null;
    public static final Item PLATE_DUROPLAST = null;
    public static final Item EMPTY_CASING = null;
    public static final Item EMPTY_SHELL = null;
    public static final Item INGOT_COPPER = null;
    public static final Item NUGGET_COPPER = null;
    public static final Item PLATE_COPPER = null;
    public static final Item DUST_COPPER = null;
    public static final Item INGOT_ALUMINIUM = null;
    public static final Item NUGGET_ALUMINIUM = null;
    public static final Item PLATE_ALUMINIUM = null;
    public static final Item DUST_ALUMINIUM = null;
    public static final Item INGOT_LEAD = null;
    public static final Item NUGGET_LEAD = null;
    public static final Item PLATE_LEAD = null;
    public static final Item DUST_LEAD = null;
    public static final Item INGOT_SILVER = null;
    public static final Item NUGGET_SILVER = null;
    public static final Item PLATE_SILVER = null;
    public static final Item DUST_SILVER = null;
    public static final Item INGOT_NICKEL = null;
    public static final Item NUGGET_NICKEL = null;
    public static final Item PLATE_NICKEL = null;
    public static final Item DUST_NICKEL = null;
    public static final Item INGOT_URANIUM = null;
    public static final Item NUGGET_URANIUM = null;
    public static final Item PLATE_URANIUM = null;
    public static final Item DUST_URANIUM = null;
    public static final Item INGOT_CONSTANTAN = null;
    public static final Item NUGGET_CONSTANTAN = null;
    public static final Item PLATE_CONSTANTAN = null;
    public static final Item DUST_CONSTANTAN = null;
    public static final Item INGOT_ELECTRUM = null;
    public static final Item NUGGET_ELECTRUM = null;
    public static final Item PLATE_ELECTRUM = null;
    public static final Item DUST_ELECTRUM = null;
    public static final Item INGOT_STEEL = null;
    public static final Item NUGGET_STEEL = null;
    public static final Item PLATE_STEEL = null;
    public static final Item DUST_STEEL = null;
    public static final Item PLATE_IRON = null;
    public static final Item DUST_IRON = null;
    public static final Item PLATE_GOLD = null;
    public static final Item DUST_GOLD = null;
    public static final Item HAMMER = null;
    public static final Item WIRECUTTER = null;
    public static final Item SCREWDRIVER = null;
    public static final Item MANUAL = null;
    public static final Item VOLTMETER = null;
    public static final Item PICKAXE_STEEL = null;
    public static final Item SHOVEL_STEEL = null;
    public static final Item AXE_STEEL = null;
    public static final Item HOE_STEEL = null;
    public static final Item SWORD_STEEL = null;
    public static final Item TOOLBOX = null;
    public static final Item DRILL = null;
    public static final Item DRILLHEAD_STEEL = null;
    public static final Item DRILLHEAD_IRON = null;
    public static final Item BUZZSAW = null;
    public static final Item SAWBLADE = null;
    public static final Item ROCKCUTTER = null;
    public static final Item GRINDING_DISK = null;
    public static final Item SURVEY_TOOLS = null;
    public static final Item GLIDER = null;
    public static final Item ARMOR_STEEL_HELMET = null;
    public static final Item ARMOR_STEEL_CHESTPLATE = null;
    public static final Item ARMOR_STEEL_LEGGINGS = null;
    public static final Item ARMOR_STEEL_BOOTS = null;
    public static final Item REVOLVER = null;
    public static final Item SPEEDLOADER = null;
    public static final Item CHEMICAL_THROWER = null;
    public static final Item RAILGUN = null;
    public static final Item CASULL_CARTRIDGE = null;
    public static final Item ARMOR_PIERCING_CARTRIDGE = null;
    public static final Item BUCKSHOT_CARTRIDGE = null;
    public static final Item HIGH_EXPLOSIVE_CARTRIDGE = null;
    public static final Item SILVER_CARTRIDGE = null;
    public static final Item DRAGONS_BREATH = null;
    public static final Item POTION_CARTRIDGE = null;
    public static final Item FLARE_CARTRIDGE = null;
    public static final Item FIREWORK_CARTRIDGE = null;
    public static final Item HOMING_CARTRIDGE = null;
    public static final Item WOLFPACK_CARTRIDGE = null;
    public static final Item MINECART_WOODEN_CRATE = null;
    public static final Item MINECART_REINFORCED_CRATE = null;
    public static final Item MINECART_WOODEN_BARREL = null;
    public static final Item MINECART_METAL_BARREL = null;
    public static final Item HEMP_SEEDS = null;
    public static final Item JERRYCAN = null;
    public static final Item BLUEPRINT = null;
    public static final Item SKYHOOK = null;
    public static final Item SHADER = null;
    public static final Item EARMUFFS = null;
    public static final Item CORE_SAMPLE = null;
    public static final Item GRAPHITE_ELECTRODE = null;
    public static final Item FLUORESCENT_TUBE = null;
    public static final Item POWERPACK = null;
    public static final Item HEAVY_SHIELD = null;
    public static final Item MAINTENANCE_KIT = null;
    public static final Item LOGIC_CIRCUIT = null;
    public static final Item FERTILIZER = null;
    public static final Item WIRECOIL_COPPER = null;
    public static final Item WIRECOIL_ELECTRUM = null;
    public static final Item WIRECOIL_STEEL = null;
    public static final Item WIRECOIL_STRUCTURE_ROPE = null;
    public static final Item WIRECOIL_STRUCTURE_STEEL = null;
    public static final Item WIRECOIL_REDSTONE = null;
    public static final Item WIRECOIL_COPPER_INSULATED = null;
    public static final Item WIRECOIL_ELECTRUM_INSULATED = null;
    public static final Item UPGRADE_DRILL_WATERPROOF = null;
    public static final Item UPGRADE_DRILL_LUBRICATION = null;
    public static final Item UPGRADE_DRILL_DAMAGE = null;
    public static final Item UPGRADE_DRILL_FORTUNE = null;
    public static final Item UPGRADE_DRILL_CAPACITY = null;
    public static final Item UPGRADE_REVOLVER_BAYONET = null;
    public static final Item UPGRADE_REVOLVER_MAGAZINE = null;
    public static final Item UPGRADE_REVOLVER_SHOCK = null;
    public static final Item UPGRADE_CHEMTHROWER_FOCUS = null;
    public static final Item UPGRADE_CHEMTHROWER_MULTITANK = null;
    public static final Item UPGRADE_RAILGUN_SCOPE = null;
    public static final Item UPGRADE_RAILGUN_CAPACITORS = null;
    public static final Item UPGRADE_SHIELD_FLASHBULB = null;
    public static final Item UPGRADE_SHIELD_SHOCK = null;
    public static final Item UPGRADE_SHIELD_MAGNET = null;
    public static final Item UPGRADE_BUZZSAW_QUIVER = null;
    public static final Item UPGRADE_POWERPACK_ANTENNA = null;
    public static final Item UPGRADE_POWERPACK_INDUCTION = null;
    public static final Item UPGRADE_POWERPACK_TESLA = null;
    public static final Item UPGRADE_POWERPACK_MAGNET = null;
    public static final Item ARMOR_FARADAY_HELMET = null;
    public static final Item ARMOR_FARADAY_CHESTPLATE = null;
    public static final Item ARMOR_FARADAY_LEGGINGS = null;
    public static final Item ARMOR_FARADAY_BOOTS = null;
    public static final Item BANNER_PATTERN_HAMMER = null;
    public static final Item BANNER_PATTERN_PLATING = null;
    public static final Item BANNER_PATTERN_ORNATE = null;
    public static final Item BANNER_PATTERN_WOODEN_PANELING = null;
    public static final Item BANNER_PATTERN_WINDMILL = null;
    public static final Item BANNER_PATTERN_WOLF_RIGHT = null;
    public static final Item BANNER_PATTERN_WOLF_LEFT = null;
    public static final Item BANNER_PATTERN_WOLF = null;
    public static final Item SHADER_BAG_COMMON = null;
    public static final Item SHADER_BAG_UNCOMMON = null;
    public static final Item SHADER_BAG_RARE = null;
    public static final Item SHADER_BAG_EPIC = null;
    public static final Item SHADER_BAG_MASTERWORK = null;

    @Override
    protected void preInit(FMLPreInitializationEvent event) {
        this.register(new Item(), "mold_plate");
        this.register(new Item(), "mold_gear");
        this.register(new Item(), "mold_rod");
        this.register(new Item(), "mold_bullet_casing");
        this.register(new Item(), "mold_wire");
        this.register(new Item(), "mold_mold_packing_4");
        this.register(new Item(), "mold_mold_packing_9");
        this.register(new Item(), "mold_unpacking");
        this.register(new Item(), "stick_treated");
        this.register(new Item(), "stick_iron");
        this.register(new Item(), "stick_steel");
        this.register(new Item(), "stick_aluminium");
        this.register(new Item(), "hemp_fiber");
        this.register(new Item(), "hemp_fabric");
        this.register(new Item(), "ersatz_leather");
        this.register(new Item(), "coal_coke");
        this.register(new Item(), "slag");
        this.register(new Item(), "component_iron");
        this.register(new Item(), "component_steel");
        this.register(new Item(), "component_electronic");
        this.register(new Item(), "component_electronic_adv");
        this.register(new Item(), "waterwheel_segment");
        this.register(new Item(), "windmill_blade");
        this.register(new Item(), "windmill_sail");
        this.register(new Item(), "wooden_grip");
        this.register(new Item(), "gunpart_barrel");
        this.register(new Item(), "gunpart_drum");
        this.register(new Item(), "gunpart_hammer");
        this.register(new Item(), "dust_coke");
        this.register(new Item(), "dust_hop_graphite");
        this.register(new Item(), "ingot_hop_graphite");
        this.register(new Item(), "wire_copper");
        this.register(new Item(), "wire_electrum");
        this.register(new Item(), "wire_aluminium");
        this.register(new Item(), "wire_steel");
        this.register(new Item(), "wire_lead");
        this.register(new Item(), "dust_saltpeter");
        this.register(new Item(), "dust_sulfur");
        this.register(new Item(), "dust_wood");
        this.register(new Item(), "light_bulb");
        this.register(new Item(), "electron_tube");
        this.register(new Item(), "circuit_board");
        this.register(new Item(), "plate_duroplast");
        this.register(new Item(), "empty_casing");
        this.register(new Item(), "empty_shell");
        this.register(new Item(), "ingot_copper");
        this.register(new Item(), "nugget_copper");
        this.register(new Item(), "plate_copper");
        this.register(new Item(), "dust_copper");
        this.register(new Item(), "ingot_aluminium");
        this.register(new Item(), "nugget_aluminium");
        this.register(new Item(), "plate_aluminium");
        this.register(new Item(), "dust_aluminium");
        this.register(new Item(), "ingot_lead");
        this.register(new Item(), "nugget_lead");
        this.register(new Item(), "plate_lead");
        this.register(new Item(), "dust_lead");
        this.register(new Item(), "ingot_silver");
        this.register(new Item(), "nugget_silver");
        this.register(new Item(), "plate_silver");
        this.register(new Item(), "dust_silver");
        this.register(new Item(), "ingot_nickel");
        this.register(new Item(), "nugget_nickel");
        this.register(new Item(), "plate_nickel");
        this.register(new Item(), "dust_nickel");
        this.register(new Item(), "ingot_uranium");
        this.register(new Item(), "nugget_uranium");
        this.register(new Item(), "plate_uranium");
        this.register(new Item(), "dust_uranium");
        this.register(new Item(), "ingot_constantan");
        this.register(new Item(), "nugget_constantan");
        this.register(new Item(), "plate_constantan");
        this.register(new Item(), "dust_constantan");
        this.register(new Item(), "ingot_electrum");
        this.register(new Item(), "nugget_electrum");
        this.register(new Item(), "plate_electrum");
        this.register(new Item(), "dust_electrum");
        this.register(new Item(), "ingot_steel");
        this.register(new Item(), "nugget_steel");
        this.register(new Item(), "plate_steel");
        this.register(new Item(), "dust_steel");
        this.register(new Item(), "plate_iron");
        this.register(new Item(), "dust_iron");
        this.register(new Item(), "plate_gold");
        this.register(new Item(), "dust_gold");
        this.register(new Item(), "hammer");
        this.register(new Item(), "wirecutter");
        this.register(new Item(), "screwdriver");
        this.register(new Item(), "manual");
        this.register(new Item(), "voltmeter");
        this.register(new ItemPickaxeBase(STEEL), "pickaxe_steel");
        this.register(new ItemSpade(STEEL), "shovel_steel");
        this.register(new ItemAxeBase(STEEL), "axe_steel");
        this.register(new ItemHoe(STEEL), "hoe_steel");
        this.register(new ItemSword(STEEL), "sword_steel");
        this.register(new Item(), "toolbox");
        this.register(new Item(), "drill");
        this.register(new Item(), "drillhead_steel");
        this.register(new Item(), "drillhead_iron");
        this.register(new Item(), "buzzsaw");
        this.register(new Item(), "sawblade");
        this.register(new Item(), "rockcutter");
        this.register(new Item(), "grinding_disk");
        this.register(new Item(), "survey_tools");
        this.register(new Item(), "glider");
        this.register(new Item(), "armor_steel_helmet");
        this.register(new Item(), "armor_steel_chestplate");
        this.register(new Item(), "armor_steel_leggings");
        this.register(new Item(), "armor_steel_boots");
        this.register(new Item(), "revolver");
        this.register(new Item(), "speedloader");
        this.register(new Item(), "chemical_thrower");
        this.register(new Item(), "railgun");
        this.register(new Item(), "casull_cartridge");
        this.register(new Item(), "armor_piercing_cartridge");
        this.register(new Item(), "buckshot_cartridge");
        this.register(new Item(), "high_explosive_cartridge");
        this.register(new Item(), "silver_cartridge");
        this.register(new Item(), "dragons_breath");
        this.register(new Item(), "potion_cartridge");
        this.register(new Item(), "flare_cartridge");
        this.register(new Item(), "firework_cartridge");
        this.register(new Item(), "homing_cartridge");
        this.register(new Item(), "wolfpack_cartridge");
        this.register(new Item(), "minecart_wooden_crate");
        this.register(new Item(), "minecart_reinforced_crate");
        this.register(new Item(), "minecart_wooden_barrel");
        this.register(new Item(), "minecart_metal_barrel");
        this.register(new Item(), "hemp_seeds");
        this.register(new Item(), "jerrycan");
        this.register(new Item(), "blueprint");
        this.register(new Item(), "skyhook");
        this.register(new Item(), "shader");
        this.register(new Item(), "earmuffs");
        this.register(new Item(), "core_sample");
        this.register(new Item(), "graphite_electrode");
        this.register(new Item(), "fluorescent_tube");
        this.register(new Item(), "powerpack");
        this.register(new Item(), "heavy_shield");
        this.register(new Item(), "maintenance_kit");
        this.register(new Item(), "logic_circuit");
        this.register(new Item(), "fertilizer");
        this.register(new Item(), "wirecoil_copper");
        this.register(new Item(), "wirecoil_electrum");
        this.register(new Item(), "wirecoil_steel");
        this.register(new Item(), "wirecoil_structure_rope");
        this.register(new Item(), "wirecoil_structure_steel");
        this.register(new Item(), "wirecoil_redstone");
        this.register(new Item(), "wirecoil_copper_insulated");
        this.register(new Item(), "wirecoil_electrum_insulated");
        this.register(new Item(), "upgrade_drill_waterproof");
        this.register(new Item(), "upgrade_drill_lubrication");
        this.register(new Item(), "upgrade_drill_damage");
        this.register(new Item(), "upgrade_drill_fortune");
        this.register(new Item(), "upgrade_drill_capacity");
        this.register(new Item(), "upgrade_revolver_bayonet");
        this.register(new Item(), "upgrade_revolver_magazine");
        this.register(new Item(), "upgrade_revolver_shock");
        this.register(new Item(), "upgrade_chemthrower_focus");
        this.register(new Item(), "upgrade_chemthrower_multitank");
        this.register(new Item(), "upgrade_railgun_scope");
        this.register(new Item(), "upgrade_railgun_capacitors");
        this.register(new Item(), "upgrade_shield_flashbulb");
        this.register(new Item(), "upgrade_shield_shock");
        this.register(new Item(), "upgrade_shield_magnet");
        this.register(new Item(), "upgrade_buzzsaw_quiver");
        this.register(new Item(), "upgrade_powerpack_antenna");
        this.register(new Item(), "upgrade_powerpack_induction");
        this.register(new Item(), "upgrade_powerpack_tesla");
        this.register(new Item(), "upgrade_powerpack_magnet");
        this.register(new Item(), "armor_faraday_helmet");
        this.register(new Item(), "armor_faraday_chestplate");
        this.register(new Item(), "armor_faraday_leggings");
        this.register(new Item(), "armor_faraday_boots");
        this.register(new Item(), "banner_pattern_hammer");
        this.register(new Item(), "banner_pattern_plating");
        this.register(new Item(), "banner_pattern_ornate");
        this.register(new Item(), "banner_pattern_wooden_paneling");
        this.register(new Item(), "banner_pattern_windmill");
        this.register(new Item(), "banner_pattern_wolf_right");
        this.register(new Item(), "banner_pattern_wolf_left");
        this.register(new Item(), "banner_pattern_wolf");
        this.register(new Item(), "shader_bag_common");
        this.register(new Item(), "shader_bag_uncommon");
        this.register(new Item(), "shader_bag_rare");
        this.register(new Item(), "shader_bag_epic");
        this.register(new Item(), "shader_bag_masterwork");
    }

    @Override
    public void register(Item entry) {
        super.register(entry.setCreativeTab(ImmersiveEngineering.MAIN));
    }
}
