package surreal.bpcatacombs.block;

import net.minecraft.block.Block;
import net.minecraft.block.material.Material;
import net.minecraft.item.Item;
import net.minecraft.item.ItemBlock;
import net.minecraft.util.ResourceLocation;
import net.minecraftforge.fml.common.event.FMLInitializationEvent;
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;
import net.minecraftforge.fml.common.registry.GameRegistry;
import net.minecraftforge.fml.common.registry.GameRegistry.ObjectHolder;
import surreal.bpcatacombs.Tags;
import surreal.bpcatacombs.internal.registration.Registry;
import surreal.bpcatacombs.item.BPCItems;
import surreal.bpcatacombs.item.ItemBlockWorkbench;
import surreal.bpcatacombs.tile.TileWorkbench;
import surreal.bpcatacombs.util.SupplierInput;

import java.util.Objects;

@ObjectHolder(Tags.MOD_ID)
public class BPCBlocks extends Registry<Block> {

    public static final Block CUSHION = null;
    public static final Block BALLOON = null;
    public static final Block STRIP_CURTAIN = null;
    public static final Block COKE_BRICK = null;
    public static final Block BLAST_BRICK = null;
    public static final Block BLAST_BRICK_REINFORCED = null;
    public static final Block SLAG_BRICK = null;
    public static final Block CLINKER_BRICKS = null;
    public static final Block CLINKER_BRICKS_SILL = null;
    public static final Block CLINKER_BRICKS_QUOIN = null;
    public static final Block COAL_COKE_BLOCK = null;
    public static final Block SLAG_GRAVEL = null;
    public static final Block GRIT_SAND = null;
    public static final Block HEMPCRETE = null;
    public static final Block HEMPCRETE_BRICK = null;
    public static final Block HEMPCRETE_BRICK_CRACKED = null;
    public static final Block HEMPCRETE_CHISELED = null;
    public static final Block HEMPCRETE_PILLAR = null;
    public static final Block CONCRETE = null;
    public static final Block CONCRETE_BRICK = null;
    public static final Block CONCRETE_BRICK_CRACKED = null;
    public static final Block CONCRETE_CHISELED = null;
    public static final Block CONCRETE_PILLAR = null;
    public static final Block CONCRETE_TILE = null;
    public static final Block CONCRETE_LEADED = null;
    public static final Block INSULATING_GLASS = null;
    public static final Block SLAG_GLASS = null;
    public static final Block CONCRETE_SPRAYED = null;
    public static final Block ALLOY_BRICK = null;
    public static final Block CONCRETE_CHUNK = null; // 8 or 12 levels
    public static final Block DUROPLAST_BLOCK = null;
    public static final Block CRAFTING_TABLE = null;
    public static final Block WORKBENCH = null;
    public static final Block CIRCUIT_TABLE = null;
    public static final Block GUNPOWDER_BARREL = null;
    public static final Block WOODEN_BARREL = null;
    public static final Block TURNTABLE = null;
    public static final Block WOODEN_CRATE = null;
    public static final Block REINFORCED_CRATE = null;
    public static final Block SORTER = null;
    public static final Block ITEM_BATCHER = null;
    public static final Block FLUID_SORTER = null;
    public static final Block WINDMILL = null;
    public static final Block WATERMILL = null;
    public static final Block TREATED_WOOD_WALLMOUNT = null;
    public static final Block LOGIC_UNIT = null;
    public static final Block RAZOR_WIRE = null;
    public static final Block CAPACITOR_LV = null;
    public static final Block CAPACITOR_MV = null;
    public static final Block CAPACITOR_HV = null;
    public static final Block CAPACITOR_CREATIVE = null;
    public static final Block METAL_BARREL = null;
    public static final Block FLUID_PUMP = null;
    public static final Block FLUID_PLACER = null;
    public static final Block BLAST_FURNACE_PREHEATER = null;
    public static final Block FURNACE_HEATER = null;
    public static final Block KINETIC_DYNAMO = null;
    public static final Block THERMOELECTRIC_GENERATOR = null;
    public static final Block ELECTRIC_LANTERN = null;
    public static final Block CHARGING_STATION = null;
    public static final Block FLUID_PIPE = null;
    public static final Block SAMPLE_DRILL = null;
    public static final Block TESLA_COIL = null;
    public static final Block FLOODLIGHT = null;
    public static final Block TURRET_CHEMTHROWER = null;
    public static final Block TURRET_GUN = null;
    public static final Block GARDEN_CLOCHE = null;
    public static final Block ELECTROMAGNET = null;
    public static final Block COIL_Lv = null;
    public static final Block COIL_MV = null;
    public static final Block COIL_HV = null;
    public static final Block REDSTONE_ENGINEERING_BLOCK = null;
    public static final Block HEAVY_ENGINEERING_BLOCK = null;
    public static final Block LIGHT_ENGINEERING_BLOCK = null;
    public static final Block GENERATOR_BLOCK = null;
    public static final Block RADIATOR_BLOCK = null;
    public static final Block STEEL_FENCE = null;
    public static final Block ALUMINIUM_FENCE = null;
    public static final Block STEEL_WALLMOUNT = null;
    public static final Block ALUMINIUM_WALLMOUNT = null;
    public static final Block STEEL_POST = null;
    public static final Block ALUMINIUM_POST = null;
    public static final Block LANTERN = null;
    public static final Block STEEL_SLOPE = null;
    public static final Block ALUMINIUM_SLOPE = null;
    public static final Block CONNECTOR_STRUCTURAL = null;
    public static final Block TRANSFORMER = null;
    public static final Block TRANSFORMER_HV = null;
    public static final Block BREAKER_SWITCH = null;
    public static final Block REDSTONE_BREAKER = null;
    public static final Block CURRENT_TRANSFORMER = null;
    public static final Block CONNECTOR_REDSTONE = null;
    public static final Block CONNECTOR_PROBE = null;
    public static final Block CONNECTOR_BUNDLED = null;
    public static final Block SHEETMETAL_COPPER = null;
    public static final Block SLAB_SHEETMETAL_COPPER = null;
    public static final Block SHEETMETAL_ALUMINIUM = null;
    public static final Block SLAB_SHEETMETAL_ALUMINIUM = null;
    public static final Block SHEETMETAL_LEAD = null;
    public static final Block SLAB_SHEETMETAL_LEAD = null;
    public static final Block SHEETMETAL_SILVER = null;
    public static final Block SLAB_SHEETMETAL_SILVER = null;
    public static final Block SHEETMETAL_NICKEL = null;
    public static final Block SLAB_SHEETMETAL_NICKEL = null;
    public static final Block SHEETMETAL_URANIUM = null;
    public static final Block SLAB_SHEETMETAL_URANIUM = null;
    public static final Block SHEETMETAL_CONSTANTAN = null;
    public static final Block SLAB_SHEETMETAL_CONSTANTAN = null;
    public static final Block SHEETMETAL_ELECTRUM = null;
    public static final Block SLAB_SHEETMETAL_ELECTRUM = null;
    public static final Block SHEETMETAL_STEEL = null;
    public static final Block SLAB_SHEETMETAL_STEEL = null;
    public static final Block SHEETMETAL_IRON = null;
    public static final Block SLAB_SHEETMETAL_IRON = null;
    public static final Block SHEETMETAL_GOLD = null;
    public static final Block SLAB_SHEETMETAL_GOLD = null;
    public static final Block ORE_COPPER = null;
    public static final Block ORE_ALUMINIUM = null;
    public static final Block ORE_LEAD = null;
    public static final Block ORE_SILVER = null;
    public static final Block ORE_NICKEL = null;
    public static final Block ORE_URANIUM = null;
    public static final Block COPPER_BLOCK = null;
    public static final Block SLAB_COPPER_BLOCK = null;
    public static final Block ALUMINIUM_BLOCK = null;
    public static final Block SLAB_ALUMINIUM_BLOCK = null;
    public static final Block LEAD_BLOCK = null;
    public static final Block SLAB_LEAD_BLOCK = null;
    public static final Block SILVER_BLOCK = null;
    public static final Block SLAB_SILVER_BLOCK = null;
    public static final Block NICKEL_BLOCK = null;
    public static final Block SLAB_NICKEL_BLOCK = null;
    public static final Block URANIUM_BLOCK = null;
    public static final Block SLAB_URANIUM_BLOCK = null;
    public static final Block CONSTANTAN_BLOCK = null;
    public static final Block SLAB_CONSTANTAN_BLOCK = null;
    public static final Block ELECTRUM_BLOCK = null;
    public static final Block SLAB_ELECTRUM_BLOCK = null;
    public static final Block STEEL_BLOCK = null;
    public static final Block SLAB_STEEL_BLOCK = null;
    public static final Block TREATED_WOOD_FENCE = null;
    public static final Block TREATED_WOOD_SCAFFOLDING = null;
    public static final Block TREATED_WOOD_POST = null;
    public static final Block SAWDUST = null;
    public static final Block FIBERBOARD = null;
    public static final Block TREATED_WOOD = null;
    public static final Block SLAB_TREATED_WOOD = null;
    public static final Block TREATED_WOOD_STAIRS = null;
    public static final Block TREATED_WOOD_VERTICAL = null;
    public static final Block SLAB_TREATED_WOOD_VERTICAL = null;
    public static final Block TREATED_WOOD_VERTICAL_STAIRS = null;
    public static final Block TREATED_WOOD_PACKAGED = null;
    public static final Block SLAB_TREATED_WOOD_PACKAGED = null;
    public static final Block TREATED_WOOD_PACKAGED_STAIRS = null;
    public static final Block WHITE_SHEETMETAL = null;
    public static final Block SLAB_WHITE_SHEETMETAL = null;
    public static final Block ORANGE_SHEETMETAL = null;
    public static final Block SLAB_ORANGE_SHEETMETAL = null;
    public static final Block MAGENTA_SHEETMETAL = null;
    public static final Block SLAB_MAGENTA_SHEETMETAL = null;
    public static final Block LIGHT_BLUE_SHEETMETAL = null;
    public static final Block SLAB_LIGHT_BLUE_SHEETMETAL = null;
    public static final Block YELLOW_SHEETMETAL = null;
    public static final Block SLAB_YELLOW_SHEETMETAL = null;
    public static final Block LIME_SHEETMETAL = null;
    public static final Block SLAB_LIME_SHEETMETAL = null;
    public static final Block PINK_SHEETMETAL = null;
    public static final Block SLAB_PINK_SHEETMETAL = null;
    public static final Block GRAY_SHEETMETAL = null;
    public static final Block SLAB_GRAY_SHEETMETAL = null;
    public static final Block LIGHT_GRAY_SHEETMETAL = null;
    public static final Block SLAB_LIGHT_GRAY_SHEETMETAL = null;
    public static final Block CYAN_SHEETMETAL = null;
    public static final Block SLAB_CYAN_SHEETMETAL = null;
    public static final Block PURPLE_SHEETMETAL = null;
    public static final Block SLAB_PURPLE_SHEETMETAL = null;
    public static final Block BLUE_SHEETMETAL = null;
    public static final Block SLAB_BLUE_SHEETMETAL = null;
    public static final Block BROWN_SHEETMETAL = null;
    public static final Block SLAB_BROWN_SHEETMETAL = null;
    public static final Block GREEN_SHEETMETAL = null;
    public static final Block SLAB_GREEN_SHEETMETAL = null;
    public static final Block RED_SHEETMETAL = null;
    public static final Block SLAB_RED_SHEETMETAL = null;
    public static final Block BLACK_SHEETMETAL = null;
    public static final Block SLAB_BLACK_SHEETMETAL = null;
    public static final Block METAL_LADDER = null;
    public static final Block METAL_LADDER_SCAFFOLDING_ALUMINIUM = null;
    public static final Block METAL_LADDER_SCAFFOLDING_STEEL = null;
    public static final Block STEEL_SCAFFOLDING = null;
    public static final Block SLAB_STEEL_SCAFFOLDING = null;
    public static final Block STAIRS_STEEL_SCAFFOLDING = null;
    public static final Block STEEL_SCAFFOLDING_GRATE = null;
    public static final Block SLAB_STEEL_SCAFFOLDING_GRATE = null;
    public static final Block STAIRS_STEEL_SCAFFOLDING_GRATE = null;
    public static final Block STEEL_SCAFFOLDING_WOOD = null;
    public static final Block SLAB_STEEL_SCAFFOLDING_WOOD = null;
    public static final Block STAIRS_STEEL_SCAFFOLDING_WOOD = null;
    public static final Block ALUMINIUM_SCAFFOLDING = null;
    public static final Block SLAB_ALUMINIUM_SCAFFOLDING = null;
    public static final Block STAIRS_ALUMINIUM_SCAFFOLDING = null;
    public static final Block ALUMINIUM_SCAFFOLDING_GRATE = null;
    public static final Block SLAB_ALUMINIUM_SCAFFOLDING_GRATE = null;
    public static final Block STAIRS_ALUMINIUM_SCAFFOLDING_GRATE = null;
    public static final Block ALUMINIUM_SCAFFOLDING_WOOD = null;
    public static final Block SLAB_ALUMINIUM_SCAFFOLDING_WOOD = null;
    public static final Block STAIRS_ALUMINIUM_SCAFFOLDING_WOOD = null;
    public static final Block SHEETMETAL_COPPER_CHUTE = null;
    public static final Block SHEETMETAL_ALUMINIUM_CHUTE = null;
    public static final Block SHEETMETAL_LEAD_CHUTE = null;
    public static final Block SHEETMETAL_SILVER_CHUTE = null;
    public static final Block SHEETMETAL_NICKEL_CHUTE = null;
    public static final Block SHEETMETAL_URANIUM_CHUTE = null;
    public static final Block SHEETMETAL_CONSTANTAN_CHUTE = null;
    public static final Block SHEETMETAL_ELECTRUM_CHUTE = null;
    public static final Block SHEETMETAL_STEEL_CHUTE = null;
    public static final Block SHEETMETAL_IRON_CHUTE = null;
    public static final Block SHEETMETAL_GOLD_CHUTE = null;
    public static final Block CONNECTOR_LV = null;
    public static final Block CONNECTOR_MV = null;
    public static final Block CONNECTOR_HV = null;
    public static final Block CONNECTOR_RELAY_LV = null;
    public static final Block CONNECTOR_RELAY_MV = null;
    public static final Block CONNECTOR_RELAY_HV = null;
    public static final Block SLAB_COKE_BRICK = null;
    public static final Block SLAB_BLAST_BRICK = null;
    public static final Block SLAB_BLAST_BRICK_REINFORCED = null;
    public static final Block SLAB_SLAG_BRICK = null;
    public static final Block SLAB_CLINKER_BRICK = null;
    public static final Block SLAB_COKE_BLOCK = null;
    public static final Block SLAB_HEMPCRETE = null;
    public static final Block SLAB_HEMPCRETE_BRICK = null;
    public static final Block SLAB_CONCRETE = null;
    public static final Block SLAB_CONCRETE_BRICK = null;
    public static final Block SLAB_CONCRETE_TILE = null;
    public static final Block SLAB_CONCRETE_LEADED = null;
    public static final Block SLAB_INSULATING_GLASS = null;
    public static final Block SLAB_ALLOY_BRICK = null;
    public static final Block STAIRS_SLAG_BRICK = null;
    public static final Block STAIRS_CLINKER_BRICK = null;
    public static final Block STAIRS_COKE_BLOCK = null;
    public static final Block STAIRS_HEMPCRETE = null;
    public static final Block STAIRS_HEMPCRETE_BRICK = null;
    public static final Block STAIRS_CONCRETE = null;
    public static final Block STAIRS_CONCRETE_BRICK = null;
    public static final Block STAIRS_CONCRETE_TILE = null;
    public static final Block STAIRS_CONCRETE_LEADED = null;
    public static final Block WALL_SLAG_BRICK = null;
    public static final Block WALL_CLINKER_BRICK = null;
    public static final Block CONVEYOR_BELT = null;
    public static final Block CONVEYOR_BELT_REDSTONE = null;
    public static final Block CONVEYOR_BELT_DROPPER = null;
    public static final Block CONVEYOR_BELT_VERTICAL = null;
    public static final Block CONVEYOR_BELT_SPLITTER = null;
    public static final Block CONVEYOR_BELT_EXTRACT = null;

    private final BPCItems items;

    public BPCBlocks(BPCItems items) {
        this.items = items;
    }

    @Override
    protected void preInit(FMLPreInitializationEvent event) {
        this.register(new BlockDull(), "cushion");
        this.register(new BlockDull(), "balloon");
        this.register(new BlockDull(), "strip_curtain");
        this.register(new BlockDull(), "coke_brick");
        this.register(new BlockDull(), "blast_brick");
        this.register(new BlockDull(), "blast_brick_reinforced");
        this.register(new BlockDull(), "slag_brick");
        this.register(new BlockDull(), "clinker_bricks");
        this.register(new BlockDull(), "clinker_bricks_sill");
        this.register(new BlockDull(), "clinker_bricks_quoin");
        this.register(new BlockDull(), "coal_coke_block");
        this.register(new BlockDull(), "slag_gravel");
        this.register(new BlockDull(), "grit_sand");
        this.register(new BlockDull(), "hempcrete");
        this.register(new BlockDull(), "hempcrete_brick");
        this.register(new BlockDull(), "hempcrete_brick_cracked");
        this.register(new BlockDull(), "hempcrete_chiseled");
        this.register(new BlockDull(), "hempcrete_pillar");
        this.register(new BlockDull(), "concrete");
        this.register(new BlockDull(), "concrete_brick");
        this.register(new BlockDull(), "concrete_brick_cracked");
        this.register(new BlockDull(), "concrete_chiseled");
        this.register(new BlockDull(), "concrete_pillar");
        this.register(new BlockDull(), "concrete_tile");
        this.register(new BlockDull(), "concrete_leaded");
        this.register(new BlockDull(), "insulating_glass");
        this.register(new BlockDull(), "slag_glass");
        this.register(new BlockDull(), "concrete_sprayed");
        this.register(new BlockDull(), "alloy_brick");
        this.register(new BlockDull(), "concrete_chunk");
        this.register(new BlockDull(), "duroplast_block");
        this.register(new BlockDull(), "crafting_table");
        this.register(new BlockWoodenWorkbench(), "workbench", ItemBlockWorkbench::new);
        this.register(new BlockDull(), "circuit_table");
        this.register(new BlockDull(), "gunpowder_barrel");
        this.register(new BlockDull(), "wooden_barrel");
        this.register(new BlockDull(), "turntable");
        this.register(new BlockDull(), "wooden_crate");
        this.register(new BlockDull(), "reinforced_crate");
        this.register(new BlockDull(), "sorter");
        this.register(new BlockDull(), "item_batcher");
        this.register(new BlockDull(), "fluid_sorter");
        this.register(new BlockDull(), "windmill");
        this.register(new BlockDull(), "watermill");
        this.register(new BlockDull(), "treated_wood_wallmount");
        this.register(new BlockDull(), "logic_unit");
        this.register(new BlockDull(), "razor_wire");
        this.register(new BlockDull(), "capacitor_lv");
        this.register(new BlockDull(), "capacitor_mv");
        this.register(new BlockDull(), "capacitor_hv");
        this.register(new BlockDull(), "capacitor_creative");
        this.register(new BlockDull(), "metal_barrel");
        this.register(new BlockDull(), "fluid_pump");
        this.register(new BlockDull(), "fluid_placer");
        this.register(new BlockDull(), "blast_furnace_preheater");
        this.register(new BlockDull(), "furnace_heater");
        this.register(new BlockDull(), "kinetic_dynamo");
        this.register(new BlockDull(), "thermoelectric_generator");
        this.register(new BlockDull(), "electric_lantern");
        this.register(new BlockDull(), "charging_station");
        this.register(new BlockDull(), "fluid_pipe");
        this.register(new BlockDull(), "sample_drill");
        this.register(new BlockDull(), "tesla_coil");
        this.register(new BlockDull(), "floodlight");
        this.register(new BlockDull(), "turret_chemthrower");
        this.register(new BlockDull(), "turret_gun");
        this.register(new BlockDull(), "garden_cloche");
        this.register(new BlockDull(), "electromagnet");
        this.register(new BlockDull(), "coil_lv");
        this.register(new BlockDull(), "coil_mv");
        this.register(new BlockDull(), "coil_hv");
        this.register(new BlockDull(), "redstone_engineering_block");
        this.register(new BlockDull(), "heavy_engineering_block");
        this.register(new BlockDull(), "light_engineering_block");
        this.register(new BlockDull(), "generator_block");
        this.register(new BlockDull(), "radiator_block");
        this.register(new BlockDull(), "steel_fence");
        this.register(new BlockDull(), "aluminium_fence");
        this.register(new BlockDull(), "steel_wallmount");
        this.register(new BlockDull(), "aluminium_wallmount");
        this.register(new BlockDull(), "steel_post");
        this.register(new BlockDull(), "aluminium_post");
        this.register(new BlockDull(), "lantern");
        this.register(new BlockDull(), "steel_slope");
        this.register(new BlockDull(), "aluminium_slope");
        this.register(new BlockDull(), "connector_structural");
        this.register(new BlockDull(), "transformer");
        this.register(new BlockDull(), "transformer_hv");
        this.register(new BlockDull(), "breaker_switch");
        this.register(new BlockDull(), "redstone_breaker");
        this.register(new BlockDull(), "current_transformer");
        this.register(new BlockDull(), "connector_redstone");
        this.register(new BlockDull(), "connector_probe");
        this.register(new BlockDull(), "connector_bundled");
        this.register(new BlockDull(), "sheetmetal_copper");
        this.register(new BlockDull(), "slab_sheetmetal_copper");
        this.register(new BlockDull(), "sheetmetal_aluminium");
        this.register(new BlockDull(), "slab_sheetmetal_aluminium");
        this.register(new BlockDull(), "sheetmetal_lead");
        this.register(new BlockDull(), "slab_sheetmetal_lead");
        this.register(new BlockDull(), "sheetmetal_silver");
        this.register(new BlockDull(), "slab_sheetmetal_silver");
        this.register(new BlockDull(), "sheetmetal_nickel");
        this.register(new BlockDull(), "slab_sheetmetal_nickel");
        this.register(new BlockDull(), "sheetmetal_uranium");
        this.register(new BlockDull(), "slab_sheetmetal_uranium");
        this.register(new BlockDull(), "sheetmetal_constantan");
        this.register(new BlockDull(), "slab_sheetmetal_constantan");
        this.register(new BlockDull(), "sheetmetal_electrum");
        this.register(new BlockDull(), "slab_sheetmetal_electrum");
        this.register(new BlockDull(), "sheetmetal_steel");
        this.register(new BlockDull(), "slab_sheetmetal_steel");
        this.register(new BlockDull(), "sheetmetal_iron");
        this.register(new BlockDull(), "slab_sheetmetal_iron");
        this.register(new BlockDull(), "sheetmetal_gold");
        this.register(new BlockDull(), "slab_sheetmetal_gold");
        this.register(new BlockDull(), "ore_copper");
        this.register(new BlockDull(), "ore_aluminium");
        this.register(new BlockDull(), "ore_lead");
        this.register(new BlockDull(), "ore_silver");
        this.register(new BlockDull(), "ore_nickel");
        this.register(new BlockDull(), "ore_uranium");
        this.register(new BlockDull(), "copper_block");
        this.register(new BlockDull(), "slab_copper_block");
        this.register(new BlockDull(), "aluminium_block");
        this.register(new BlockDull(), "slab_aluminium_block");
        this.register(new BlockDull(), "lead_block");
        this.register(new BlockDull(), "slab_lead_block");
        this.register(new BlockDull(), "silver_block");
        this.register(new BlockDull(), "slab_silver_block");
        this.register(new BlockDull(), "nickel_block");
        this.register(new BlockDull(), "slab_nickel_block");
        this.register(new BlockDull(), "uranium_block");
        this.register(new BlockDull(), "slab_uranium_block");
        this.register(new BlockDull(), "constantan_block");
        this.register(new BlockDull(), "slab_constantan_block");
        this.register(new BlockDull(), "electrum_block");
        this.register(new BlockDull(), "slab_electrum_block");
        this.register(new BlockDull(), "steel_block");
        this.register(new BlockDull(), "slab_steel_block");
        this.register(new BlockDull(), "treated_wood_fence");
        this.register(new BlockDull(), "treated_wood_scaffolding");
        this.register(new BlockDull(), "treated_wood_post");
        this.register(new BlockDull(), "sawdust");
        this.register(new BlockDull(), "fiberboard");
        this.register(new BlockDull(), "treated_wood");
        this.register(new BlockDull(), "slab_treated_wood");
        this.register(new BlockDull(), "treated_wood_stairs");
        this.register(new BlockDull(), "treated_wood_vertical");
        this.register(new BlockDull(), "slab_treated_wood_vertical");
        this.register(new BlockDull(), "treated_wood_vertical_stairs");
        this.register(new BlockDull(), "treated_wood_packaged");
        this.register(new BlockDull(), "slab_treated_wood_packaged");
        this.register(new BlockDull(), "treated_wood_packaged_stairs");
        this.register(new BlockDull(), "white_sheetmetal");
        this.register(new BlockDull(), "slab_white_sheetmetal");
        this.register(new BlockDull(), "orange_sheetmetal");
        this.register(new BlockDull(), "slab_orange_sheetmetal");
        this.register(new BlockDull(), "magenta_sheetmetal");
        this.register(new BlockDull(), "slab_magenta_sheetmetal");
        this.register(new BlockDull(), "light_blue_sheetmetal");
        this.register(new BlockDull(), "slab_light_blue_sheetmetal");
        this.register(new BlockDull(), "yellow_sheetmetal");
        this.register(new BlockDull(), "slab_yellow_sheetmetal");
        this.register(new BlockDull(), "lime_sheetmetal");
        this.register(new BlockDull(), "slab_lime_sheetmetal");
        this.register(new BlockDull(), "pink_sheetmetal");
        this.register(new BlockDull(), "slab_pink_sheetmetal");
        this.register(new BlockDull(), "gray_sheetmetal");
        this.register(new BlockDull(), "slab_gray_sheetmetal");
        this.register(new BlockDull(), "light_gray_sheetmetal");
        this.register(new BlockDull(), "slab_light_gray_sheetmetal");
        this.register(new BlockDull(), "cyan_sheetmetal");
        this.register(new BlockDull(), "slab_cyan_sheetmetal");
        this.register(new BlockDull(), "purple_sheetmetal");
        this.register(new BlockDull(), "slab_purple_sheetmetal");
        this.register(new BlockDull(), "blue_sheetmetal");
        this.register(new BlockDull(), "slab_blue_sheetmetal");
        this.register(new BlockDull(), "brown_sheetmetal");
        this.register(new BlockDull(), "slab_brown_sheetmetal");
        this.register(new BlockDull(), "green_sheetmetal");
        this.register(new BlockDull(), "slab_green_sheetmetal");
        this.register(new BlockDull(), "red_sheetmetal");
        this.register(new BlockDull(), "slab_red_sheetmetal");
        this.register(new BlockDull(), "black_sheetmetal");
        this.register(new BlockDull(), "slab_black_sheetmetal");
        this.register(new BlockDull(), "metal_ladder");
        this.register(new BlockDull(), "metal_ladder_scaffolding_aluminium");
        this.register(new BlockDull(), "metal_ladder_scaffolding_steel");
        this.register(new BlockDull(), "steel_scaffolding");
        this.register(new BlockDull(), "slab_steel_scaffolding");
        this.register(new BlockDull(), "stairs_steel_scaffolding");
        this.register(new BlockDull(), "steel_scaffolding_grate");
        this.register(new BlockDull(), "slab_steel_scaffolding_grate");
        this.register(new BlockDull(), "stairs_steel_scaffolding_grate");
        this.register(new BlockDull(), "steel_scaffolding_wood");
        this.register(new BlockDull(), "slab_steel_scaffolding_wood");
        this.register(new BlockDull(), "stairs_steel_scaffolding_wood");
        this.register(new BlockDull(), "aluminium_scaffolding");
        this.register(new BlockDull(), "slab_aluminium_scaffolding");
        this.register(new BlockDull(), "stairs_aluminium_scaffolding");
        this.register(new BlockDull(), "aluminium_scaffolding_grate");
        this.register(new BlockDull(), "slab_aluminium_scaffolding_grate");
        this.register(new BlockDull(), "stairs_aluminium_scaffolding_grate");
        this.register(new BlockDull(), "aluminium_scaffolding_wood");
        this.register(new BlockDull(), "slab_aluminium_scaffolding_wood");
        this.register(new BlockDull(), "stairs_aluminium_scaffolding_wood");
        this.register(new BlockDull(), "sheetmetal_copper_chute");
        this.register(new BlockDull(), "sheetmetal_aluminium_chute");
        this.register(new BlockDull(), "sheetmetal_lead_chute");
        this.register(new BlockDull(), "sheetmetal_silver_chute");
        this.register(new BlockDull(), "sheetmetal_nickel_chute");
        this.register(new BlockDull(), "sheetmetal_uranium_chute");
        this.register(new BlockDull(), "sheetmetal_constantan_chute");
        this.register(new BlockDull(), "sheetmetal_electrum_chute");
        this.register(new BlockDull(), "sheetmetal_steel_chute");
        this.register(new BlockDull(), "sheetmetal_iron_chute");
        this.register(new BlockDull(), "sheetmetal_gold_chute");
        this.register(new BlockDull(), "connector_lv");
        this.register(new BlockDull(), "connector_mv");
        this.register(new BlockDull(), "connector_hv");
        this.register(new BlockDull(), "connector_relay_lv");
        this.register(new BlockDull(), "connector_relay_mv");
        this.register(new BlockDull(), "connector_relay_hv");
        this.register(new BlockDull(), "slab_coke_brick");
        this.register(new BlockDull(), "slab_blast_brick");
        this.register(new BlockDull(), "slab_blast_brick_reinforced");
        this.register(new BlockDull(), "slab_slag_brick");
        this.register(new BlockDull(), "slab_clinker_brick");
        this.register(new BlockDull(), "slab_coke_block");
        this.register(new BlockDull(), "slab_hempcrete");
        this.register(new BlockDull(), "slab_hempcrete_brick");
        this.register(new BlockDull(), "slab_concrete");
        this.register(new BlockDull(), "slab_concrete_brick");
        this.register(new BlockDull(), "slab_concrete_tile");
        this.register(new BlockDull(), "slab_concrete_leaded");
        this.register(new BlockDull(), "slab_insulating_glass");
        this.register(new BlockDull(), "slab_alloy_brick");
        this.register(new BlockDull(), "stairs_slag_brick");
        this.register(new BlockDull(), "stairs_clinker_brick");
        this.register(new BlockDull(), "stairs_coke_block");
        this.register(new BlockDull(), "stairs_hempcrete");
        this.register(new BlockDull(), "stairs_hempcrete_brick");
        this.register(new BlockDull(), "stairs_concrete");
        this.register(new BlockDull(), "stairs_concrete_brick");
        this.register(new BlockDull(), "stairs_concrete_tile");
        this.register(new BlockDull(), "stairs_concrete_leaded");
        this.register(new BlockDull(), "wall_slag_brick");
        this.register(new BlockDull(), "wall_clinker_brick");
        this.register(new BlockDull(), "conveyor_belt");
        this.register(new BlockDull(), "conveyor_belt_redstone");
        this.register(new BlockDull(), "conveyor_belt_dropper");
        this.register(new BlockDull(), "conveyor_belt_vertical");
        this.register(new BlockDull(), "conveyor_belt_splitter");
        this.register(new BlockDull(), "conveyor_belt_extract");
    }

    @Override
    protected void init(FMLInitializationEvent event) {
        GameRegistry.registerTileEntity(TileWorkbench.class, new ResourceLocation(Tags.MOD_ID, "workbench"));
    }

    private <T extends Block> void register(T entry, String name, SupplierInput<T, Item> itemSupplier) {
        entry.setRegistryName(Tags.MOD_ID, name).setTranslationKey(Tags.MOD_ID + "." + name);
        Item item = itemSupplier.get(entry).setRegistryName(Objects.requireNonNull(entry.getRegistryName()));
        this.items.register(item);
        this.register(entry);
    }

    @Override
    protected void register(Block entry) {
        Item item = new ItemBlock(entry).setRegistryName(Objects.requireNonNull(entry.getRegistryName()));
        this.items.register(item);
        super.register(entry);
    }

    private static class BlockDull extends Block {

        public BlockDull() {
            super(Material.ROCK);
        }
    }
}
